root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server.exe ./cmd/server/"
  entrypoint = "./tmp/server.exe"
  delay = 500
  exclude_dir = ["assets", "tmp", "vendor", ".git", ".github"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go", "json"]
  kill_delay = 500

[log]
  time = true

[misc]
  clean_on_exit = true
